### PR TITLE
fix: mark secret outputs sensitive for classic vpn Ref: #158

### PR DESCRIPTION
**Pull request by qbaze**

### CODE REVIEW

**Comment by imrannayer** [comment]
@qbaze have you tried setting these outputs sensitive in your roor module code?

**Comment by qbaze** [comment]
@imrannayer sorry for a late response

when used as a submodule it works fine but isn't it to work also as a standalone one?

are there any cons marking these sensitive in its own outputs?

**Comment by imrannayer** [comment]
@qbaze these are published as modules. Expectation is they will be used as module. I can review the PR if available for this.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
