### PR TITLE
fix for bug reading advertise_ip_ranges = map(string) and ip_ranges =…

### PR DESCRIPTION
**Pull request by lorirava**
old code take the "key" of the map(string) and put it into the "range" of the ip_ranges. 
It is wrong. It should take the "value" of the map(string)

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
I'm not sure why these need to be reversed. It's okay to have the range as the key with the description as the value.

@lorirava is this not working for you?

**Comment by lorirava** [comment]
Hi Morgante,
is ok but you need to describe in the doc correctly. Because for example in:
https://registry.terraform.io/modules/terraform-google-modules/vpn/google/latest/submodules/vpn_ha

bgp_peer = {
        address = "169.254.1.1"
        asn     = 64513
      }

the key is a string "address" and could be used like description.
And the value is the ip.

Instead for "advertise_ip_ranges" I had to set:
advertise_ip_ranges = {
          "10.89.118.200/29" = "fileStore network"
        }
and the behaviour is the opposite.
the key is the ips, and the value is the description.

In the readme file about is described: advertise_ip_ranges = map(string)
But there are no examples.

So only with debug I can see the key-value behaviour.

Thanks for attention
Lorenzo

Il giorno lun 13 set 2021 alle ore 17:42 Morgante Pell <
***@***.***> ha scritto:

**Comment by morgante** [comment]
Yes we definitely need to fix this in the docs - if you wanted to update this PR to fix the doc that would be great!

**Comment by lorirava** [comment]
do you want I will add the doc definition without changes the
implementation like my PR?
Or my PR is correct and you want also a doc better definition?



Il giorno lun 13 set 2021 alle ore 18:02 Morgante Pell <
***@***.***> ha scritto:

**Comment by morgante** [comment]
I want to fix the docs without changing the implementation.

**Comment by morgante** [comment]
@lorirava You need to regenerate docs. Please always continue to check for lint failures after you push.

**Pull request closed without merging**
