### PR TITLE
feat: adding labels to external VPN gateway

### PR DESCRIPTION
**Pull request by yooknee**
Only the VPN Tunnel labels were added in commit: https://github.com/terraform-google-modules/terraform-google-vpn/commit/c2e563b4d5cf6b907898fd56f287fcbbb72274b5

added missing labels for the VPN external gateway

### CODE REVIEW

**Comment by imrannayer** [comment]
@yooknee can you plz bump min version required to [4.53](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4530-february-13-2023) as this feature was part of that release.

**Comment by yooknee** [comment]
@imrannayer the actual feature of having labels for the VPN module was introduced in https://github.com/terraform-google-modules/terraform-google-vpn/commit/c2e563b4d5cf6b907898fd56f287fcbbb72274b5 (but only assigned to this resource "google_compute_vpn_tunnel")

So my PR would be more of a bug since a resource "google_compute_external_vpn_gateway" that also supports labels within that module was not given those. This causes issues when pipelines have checks for labels and such (because one resource ends up having now labels while the other doesn't).

**Comment by imrannayer** [comment]
@yooknee The reason why https://github.com/terraform-google-modules/terraform-google-vpn/commit/c2e563b4d5cf6b907898fd56f287fcbbb72274b5 did not added labels to `google_compute_external_vpn_gateway` cos it was not supported at the moment. It was released as part of 4.53 which is why you will need to change min version in [version.tf](https://github.com/terraform-google-modules/terraform-google-vpn/blob/master/modules/vpn_ha/versions.tf) for [google](https://github.com/terraform-google-modules/terraform-google-vpn/blob/5953324a88959d290392cc8ab095a2079d70fc67/modules/vpn_ha/versions.tf#L22) and [google-beta](https://github.com/terraform-google-modules/terraform-google-vpn/blob/5953324a88959d290392cc8ab095a2079d70fc67/modules/vpn_ha/versions.tf#L26).

**Comment by imrannayer** [comment]
fixed in #112

**Pull request closed without merging**
